### ISSUE TITLE
Add support for ARMv8

### ISSUE THREAD

**Issue by zhiyisun** [thoughtpolice/enable_arm_pmu#1]
Currently, this code works for ARMv7 A series. I am adding ARMv8 support for it.

**Comment by hbiyik** [comment]
https://github.com/hbiyik/armpmu/

take a loot at here, for armv6/armv7/armv8/aarch32/aarch64.

**Comment by zhiyisun** [comment]
Good to know this. 

BTW, my implementation for ARMv8 support.  https://github.com/zhiyisun/enable_arm_pmu. 

Merry Christmas.
